### PR TITLE
Adding new value for Entertainment

### PR DESCRIPTION
**Pull request by soonland**
When creating a new Entertainment group for music, in the Hue app on iOS, the class value is set to "Free", which was not a valid value.

### CODE REVIEW

**Comment by michaelgira23** [comment]
Thank you for this fix @soonland! I encountered this error too. Would love to get this merged soon if possible.

**Comment by peter-murray** [comment]
Sorry, I missed this PR, but recently encountered this in my setup and fixed it in `2.0.3` release for `entertainment`. On my configuration `Free` is still not a valid value for a Room group type. Do you have confirmation that you are able to set this on your bridge? Can you share details on your version of the bridge or room configuration object that does have this set for the `class` attribute?

**Comment by soonland** [comment]
Here's the Entertainment configuration that I just created today :

```
        "200": {
            "name": "Espace Musique 2",
            "lights": [
                "4",
                "2"
            ],
            "sensors": [],
            "type": "Entertainment",
            "state": {
                "all_on": false,
                "any_on": false
            },
            "recycle": false,
            "class": "Free",
            "stream": {
                "proxymode": "auto",
                "proxynode": "/bridge",
                "active": false,
                "owner": null
            },
            "locations": {
                "4": [
                    1.00,
                    0.88,
                    0.00
                ],
                "2": [
                    -1.00,
                    1.00,
                    0.00
                ]
            },
            "action": {
                "on": false,
                "bri": 254,
                "hue": 7726,
                "sat": 197,
                "effect": "none",
                "xy": [
                    0.4994,
                    0.4153
                ],
                "ct": 443,
                "alert": "select",
                "colormode": "ct"
            }
        },
```

Here's the bridge info :

Screen Shot 2022-02-22 at 10 05 37 AM

Hope that helps !

**Comment by peter-murray** [comment]
Thank you, that should now be covered by the `2.0.3` release of this library

**Comment by soonland** [comment]
I'm sorry, I can't make it work with `2.0.3`, but it works great with `2.0.4` ! Thanks !

**Pull request closed without merging**
